services:
  db:
    build:
      context: ./docker/db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
    volumes:
      - postgres:/var/lib/postgresql
      - ./docker/db:/docker-entrypoint-initdb.d
    ports:
      - ${DB_PORT:?}:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 3s
      retries: 3

  valkey:
    image: valkey/valkey:9.1.1-alpine3.24
    command: valkey-server --save "" --appendonly no
    ports:
      - ${VALKEY_PORT:?}:6379
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 3

volumes:
  postgres:
