version: "3.8"

services:
  db:
    image: postgres:14.1-bullseye
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - ${DB_PORT:?}:5432

volumes:
  postgres:
