version: "3.8"

services:
  app:
    image: apollo-prisma-test-dev-app:1.0.0
    build:
      context: dockerfiles/dev/app
    working_dir: /app
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - yarn-cache:/usr/local/share/.cache/yarn/v6
      - jest-cache:/tmp/jest_0
    command: sh -c "yarn setup && yarn dev"
    ports:
      - ${APP_PORT:-4000}:4000
    depends_on:
      - db

  studio:
    image: apollo-prisma-test-dev-studio:1.0.0
    build:
      context: dockerfiles/dev/studio
    working_dir: /studio
    volumes:
      - ./prisma:/studio/prisma
      - ./.env:/studio/.env
      - node_modules:/studio/node_modules
    # アプリコンテナのprismaを使うので待つ
    command: sh -c "wait-for-it app:4000 --timeout=0 -- npx prisma studio"
    ports:
      - ${STUDIO_PORT:-5555}:5555
    depends_on:
      - app
      - db

  db:
    image: postgres:14.1-bullseye
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - ${DB_PORT:-5432}:5432

volumes:
  node_modules:
  yarn-cache:
  jest-cache:
  postgres:
