version: "3.8"

services:
  app:
    image: node:16.16.0-bullseye-slim
    working_dir: /app
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
      - yarn-cache:/usr/local/share/.cache/yarn/v6
      - jest-cache:/tmp/jest_0
    tty: true
    ports:
      - 4000:4000
      - 5555:5555
    depends_on:
      - db

  db:
    image: postgres:14.1-bullseye
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  node_modules:
  yarn-cache:
  jest-cache:
  postgres:
