version: "3.8"

services:
  app:
    image: apollo-prisma-test-dev-app:1.0.0
    build:
      context: dockerfiles/dev/app
    working_dir: /app
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
      - yarn-cache:/usr/local/share/.cache/yarn/v6
      - jest-cache:/tmp/jest_0
    tty: true
    ports:
      - ${APP_PORT:-4000}:4000
      - ${STUDIO_PORT:-5555}:5555
    depends_on:
      - db

  db:
    image: postgres:14.1-bullseye
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - ${DB_PORT:-5432}:5432

volumes:
  node_modules:
  yarn-cache:
  jest-cache:
  postgres:
