[tools]
node = "24.10"

[settings]
env_shell_expand = true

[env]
_.file = ".env"
_.path = ['{{config_root}}/node_modules/.bin']

[tasks.setup]
depends = ["setup:env"]
env = { _.file = ".env" } # dependsで.envが作成される場合があるので必要
run = """
pnpm install
docker compose down -v
docker compose up --wait
atlas schema --env env apply --auto-approve
node db/seed.ts
"""

[tasks."setup:env"]
hide = true
run = """
test -f .env || cp .env.example .env
"""

[tasks.dev]
depends = ["db:up"]
run = """
node --watch src/presentation/server.ts
"""

[tasks.check]
depends = ["check:*"]

[tasks."check:type"]
run = """
tsgo
"""

[tasks."check:style"]
run = """
oxlint
"""

[tasks."check:format"]
run = """
oxfmt --check
"""

[tasks.build]
run = """
vite build
"""

[tasks.preview]
depends = ["build", "db:up"]
env = { _.file = [".env.preview"] }
run = """
node --enable-source-maps dist/server.js
"""

[tasks.test]
depends = ["test:ut", "test:it", "test:e2e"]

[tasks."test:ut"]
env = { _.file = [".env.test"] }
run = """
vitest --project ut
"""

[tasks."test:it"]
depends = ["test:setup-db"]
env = { _.file = [".env.test"] }
run = """
vitest --project it
"""

[tasks."test:e2e"]
depends = ["test:setup-db"]
wait_for = ["test:it"]
env = { _.file = [".env.test"] }
run = """
vitest --project e2e
"""

[tasks."test:setup-db"]
hide = true
depends = ["db:up"]
env = { _.file = [".env.test"] }
run = """
atlas schema --env env clean --auto-approve
atlas schema --env env apply --auto-approve
"""

[tasks."db:schema"]
depends = ["db:up"]
run = """
atlas schema --env env
"""

[tasks."db:typegen"]
depends = ["db:up"]
run = """
kysely-codegen --config-file kysely-codegen.ts
"""

[tasks."db:seed"]
depends = ["db:up"]
run = """
node db/seed.ts
"""

[tasks."db:up"]
hide = true
run = """
docker compose up --wait
"""

[tasks."gql:codegen"]
run = """
node schemagen.ts
oxfmt schema.graphql
graphql-codegen-esm
"""
