/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { Uuid } from "../../../lib/uuid/vn.ts";
import type { ColumnType } from "kysely";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type TodoStatus = "done" | "pending";

export type UserRole = "admin" | "user";

export interface Credentials {
  password: string;
  userId: Uuid;
}

export interface RefreshTokens {
  createdAt: Timestamp;
  token: string;
  userId: Uuid;
}

export interface Todos {
  createdAt: Timestamp;
  description: string;
  id: Uuid;
  status: TodoStatus;
  title: string;
  updatedAt: Timestamp;
  userId: Uuid;
}

export interface Users {
  createdAt: Timestamp;
  email: string;
  id: Uuid;
  name: string;
  role: UserRole;
  updatedAt: Timestamp;
}

export interface DB {
  credentials: Credentials;
  refreshTokens: RefreshTokens;
  todos: Todos;
  users: Users;
}
