/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type Todostatus = "DONE" | "PENDING";

export type Userrole = "ADMIN" | "USER";

export interface Todo {
  description: string;
  id: string;
  status: Todostatus;
  title: string;
  updatedAt: Timestamp;
  userId: string;
}

export interface User {
  email: string;
  id: string;
  name: string;
  role: Userrole;
  updatedAt: Timestamp;
}

export interface UserCredential {
  password: string;
  updatedAt: Timestamp;
  userId: string;
}

export interface UserToken {
  token: string;
  updatedAt: Timestamp;
  userId: string;
}

export interface DB {
  Todo: Todo;
  User: User;
  UserCredential: UserCredential;
  UserToken: UserToken;
}
