/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type TodoStatus = "done" | "pending";

export type UserRole = "admin" | "user";

export interface Todos {
  createdAt: Timestamp;
  description: string;
  id: string;
  status: TodoStatus;
  title: string;
  updatedAt: Timestamp;
  userId: string;
}

export interface UserCredentials {
  password: string;
  userId: string;
}

export interface Users {
  createdAt: Timestamp;
  email: string;
  id: string;
  name: string;
  role: UserRole;
  updatedAt: Timestamp;
}

export interface UserTokens {
  lastUsedAt: Timestamp;
  refreshToken: string;
  userId: string;
}

export interface DB {
  todos: Todos;
  userCredentials: UserCredentials;
  users: Users;
  userTokens: UserTokens;
}
